INSERT INTO VOTES(voteType, itemID,candidateID, username) VALUES ('position',1,1,'peachwind18');
INSERT INTO VOTES(voteType, itemID,candidateID, username) VALUES ('position',1,1,'chestnutrainbow1');
INSERT INTO VOTES(voteType, itemID,candidateID,username) VALUES ('position',1,2,'sealstorm15');
INSERT INTO VOTES(voteType, itemID,candidateID, username) VALUES ('position',2,3,'peachwind18');
INSERT INTO VOTES(voteType, itemID,candidateID, username) VALUES ('position',2,5,'chestnutrainbow1');
INSERT INTO VOTES(voteType, itemID,candidateID,username) VALUES ('position',2,5,'sealstorm15');
INSERT INTO VOTES(voteType,itemID,initiativeResponse,username) VALUES ('initiative',5000,'yes','peachwind18');
INSERT INTO VOTES(voteType,itemID,initiativeResponse,username) VALUES ('initiative',5000,'yes','chestnutrainbow1');
INSERT INTO VOTES(voteType,itemID,initiativeResponse,username) VALUES ('initiative',5000,'no','sealstorm15');
INSERT INTO VOTES(voteType,itemID,initiativeResponse,username) VALUES ('initiative',5001,'no','peachwind18');
INSERT INTO VOTES(voteType,itemID,initiativeResponse,username) VALUES ('initiative',5001,'yes','chestnutrainbow1');
INSERT INTO VOTES(voteType,itemID,initiativeResponse,username) VALUES ('initiative',5001,'yes','sealstorm15');
INSERT INTO ballots_users VALUES(1,'peachwind18');
INSERT INTO ballots_users VALUES(1,'chestnutrainbow1');
INSERT INTO ballots_users VALUES(1,'sealstorm15');
