INSERT INTO society (societyID, societyName, societyDescription) VALUES (1, 'American Medical Association', 'Medicine');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (2, 'American Psychological Association', 'Psychology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (3, 'Institute of Electrical and Electronics Engineers', 'Electrical Engineering');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (4, 'American Chemical Society', 'Chemistry');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (5, 'American Bar Association', 'Law');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (6, 'American Society of Civil Engineers', 'Civil Engineering');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (7, 'American Institute of Architects', 'Architecture');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (8, 'American Academy of Pediatrics', 'Pediatrics');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (9, 'American Society of Mechanical Engineers', 'Mechanical Engineering');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (10, 'American Institute of Chemical Engineers', 'Chemical Engineering');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (11, 'American Nurses Association', 'Nursing');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (12, 'American Physical Society', 'Physics');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (13, 'American Society for Microbiology', 'Microbiology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (14, 'American Marketing Association', 'Marketing');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (15, 'American Mathematical Society', 'Mathematics');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (16, 'American Society of Clinical Oncology', 'Oncology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (17, 'American Dental Association', 'Dentistry');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (18, 'American Academy of Family Physicians', 'Family Medicine');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (19, 'American College of Cardiology', 'Cardiology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (20, 'American Society of Anesthesiologists', 'Anesthesiology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (21, 'American Institute of Certified Public Accountants', 'Accounting');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (22, 'American Society for Biochemistry and Molecular Biology', 'Biochemistry and Molecular Biology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (23, 'American Historical Association', 'History');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (24, 'American Institute of Physics', 'Physics');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (25, 'American Society of Agricultural and Biological Engineers', 'Agricultural and Biological Engineering');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (26, 'American Academy of Orthopaedic Surgeons', 'Orthopaedics');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (27, 'American Academy of Dermatology', 'Dermatology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (28, 'American Society for Clinical Laboratory Science', 'Clinical Laboratory Science');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (29, 'American Society of Health-System Pharmacists', 'Pharmacy');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (30, 'American Society of Hematology', 'Hematology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (31, 'American College of Physicians', 'Internal Medicine');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (32, 'American Academy of Ophthalmology', 'Ophthalmology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (33, 'American Society of Human Genetics', 'Human Genetics');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (34, 'American Society of Landscape Architects', 'Landscape Architecture');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (35, 'American College of Emergency Physicians', 'Emergency Medicine');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (36, 'American Society for Nutrition', 'Nutrition');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (37, 'American Society of Interior Designers', 'Interior Design');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (38, 'American Urological Association', 'Urology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (39, 'American Academy of Neurology', 'Neurology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (40, 'American College of Surgeons', 'Surgery');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (41, 'American Society for Engineering Education', 'Engineering Education');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (42, 'American Academy of Pediatrics - Dentistry', 'Pediatric Dentistry');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (43, 'American Institute of Aeronautics and Astronautics', 'Aeronautics and Astronautics');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (44, 'American Society for Nondestructive Testing', 'Nondestructive Testing');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (45, 'American Physical Therapy Association', 'Physical Therapy');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (46, 'American Society of Nephrology', 'Nephrology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (47, 'American College of Sports Medicine', 'Sports Medicine');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (48, 'American Society for Cell Biology', 'Cell Biology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (49, 'American Academy of Periodontology', 'Periodontology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (50, 'American Geophysical Union', 'Geophysics');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (51, 'American Anthropological Association', 'Anthropology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (52, 'American Academy of Allergy, Asthma & Immunology', 'Allergy, Asthma & Immunology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (53, 'American Society for Quality', 'Quality Management');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (54, 'American Society for Pharmacology and Experimental Therapeutics', 'Pharmacology and Experimental Therapeutics');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (55, 'American Society for Reproductive Medicine', 'Reproductive Medicine');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (56, 'American College of Rheumatology', 'Rheumatology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (57, 'American Association of Colleges of Pharmacy', 'Pharmacy Education');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (58, 'American Society for Gastrointestinal Endoscopy', 'Gastroenterology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (59, 'American Academy of Forensic Sciences', 'Forensic Science');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (60, 'American Society for Clinical Investigation', 'Clinical Investigation');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (61, 'American Academy of Child and Adolescent Psychiatry', 'Child and Adolescent Psychiatry');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (62, 'American Society for Bioethics and Humanities', 'Bioethics and Humanities');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (63, 'American Society for Clinical Pathology', 'Clinical Pathology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (64, 'American Academy of Addiction Psychiatry', 'Addiction Psychiatry');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (65, 'American Society of Andrology', 'Andrology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (66, 'American Academy of Audiology', 'Audiology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (67, 'American Statistical Association', 'Statistics');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (68, 'American Association of Nurse Practitioners', 'Nurse Practitioners');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (69, 'American Academy of Cosmetic Dentistry', 'Cosmetic Dentistry');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (70, 'American Society of Safety Professionals', 'Safety');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (71, 'American Academy of Physical Medicine and Rehabilitation', 'Physical Medicine and Rehabilitation');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (72, 'American Association for Cancer Research', 'Cancer Research');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (73, 'American College of Healthcare Executives', 'Healthcare Management');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (74, 'American Society of Clinical Hypnosis', 'Clinical Hypnosis');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (75, 'American Society of Tropical Medicine and Hygiene', 'Tropical Medicine and Hygiene');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (76, 'American Association of Pharmaceutical Scientists', 'Pharmaceutical Sciences');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (77, 'American Association of Immunologists', 'Immunology');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (78, 'American Society of Addiction Medicine', 'Addiction Medicine');
INSERT INTO society (societyID, societyName, societyDescription) VALUES (79, 'American Association of Physicists in Medicine', 'Medical Physics');
