INSERT INTO society (societyName, societyDescription) VALUES ('American Medical Association', 'Medicine');
INSERT INTO society (societyName, societyDescription) VALUES ('American Psychological Association', 'Psychology');
INSERT INTO society (societyName, societyDescription) VALUES ('Institute of Electrical and Electronics Engineers', 'Electrical Engineering');
INSERT INTO society (societyName, societyDescription) VALUES ('American Chemical Society', 'Chemistry');
INSERT INTO society (societyName, societyDescription) VALUES ('American Bar Association', 'Law');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Civil Engineers', 'Civil Engineering');
INSERT INTO society (societyName, societyDescription) VALUES ('American Institute of Architects', 'Architecture');
INSERT INTO society (societyName, societyDescription) VALUES ('American Academy of Pediatrics', 'Pediatrics');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Mechanical Engineers', 'Mechanical Engineering');
INSERT INTO society (societyName, societyDescription) VALUES ('American Institute of Chemical Engineers', 'Chemical Engineering');
INSERT INTO society (societyName, societyDescription) VALUES ('American Nurses Association', 'Nursing');
INSERT INTO society (societyName, societyDescription) VALUES ('American Physical Society', 'Physics');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society for Microbiology', 'Microbiology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Marketing Association', 'Marketing');
INSERT INTO society (societyName, societyDescription) VALUES ('American Mathematical Society', 'Mathematics');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Clinical Oncology', 'Oncology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Dental Association', 'Dentistry');
INSERT INTO society (societyName, societyDescription) VALUES ('American Academy of Family Physicians', 'Family Medicine');
INSERT INTO society (societyName, societyDescription) VALUES ('American College of Cardiology', 'Cardiology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Anesthesiologists', 'Anesthesiology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Institute of Certified Public Accountants', 'Accounting');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society for Biochemistry and Molecular Biology', 'Biochemistry and Molecular Biology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Historical Association', 'History');
INSERT INTO society (societyName, societyDescription) VALUES ('American Institute of Physics', 'Physics');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Agricultural and Biological Engineers', 'Agricultural and Biological Engineering');
INSERT INTO society (societyName, societyDescription) VALUES ('American Academy of Orthopaedic Surgeons', 'Orthopaedics');
INSERT INTO society (societyName, societyDescription) VALUES ('American Academy of Dermatology', 'Dermatology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society for Clinical Laboratory Science', 'Clinical Laboratory Science');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Health-System Pharmacists', 'Pharmacy');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Hematology', 'Hematology');
INSERT INTO society (societyName, societyDescription) VALUES ('American College of Physicians', 'Internal Medicine');
INSERT INTO society (societyName, societyDescription) VALUES ('American Academy of Ophthalmology', 'Ophthalmology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Human Genetics', 'Human Genetics');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Landscape Architects', 'Landscape Architecture');
INSERT INTO society (societyName, societyDescription) VALUES ('American College of Emergency Physicians', 'Emergency Medicine');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society for Nutrition', 'Nutrition');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Interior Designers', 'Interior Design');
INSERT INTO society (societyName, societyDescription) VALUES ('American Urological Association', 'Urology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Academy of Neurology', 'Neurology');
INSERT INTO society (societyName, societyDescription) VALUES ('American College of Surgeons', 'Surgery');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society for Engineering Education', 'Engineering Education');
INSERT INTO society (societyName, societyDescription) VALUES ('American Academy of Pediatrics - Dentistry', 'Pediatric Dentistry');
INSERT INTO society (societyName, societyDescription) VALUES ('American Institute of Aeronautics and Astronautics', 'Aeronautics and Astronautics');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society for Nondestructive Testing', 'Nondestructive Testing');
INSERT INTO society (societyName, societyDescription) VALUES ('American Physical Therapy Association', 'Physical Therapy');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Nephrology', 'Nephrology');
INSERT INTO society (societyName, societyDescription) VALUES ('American College of Sports Medicine', 'Sports Medicine');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society for Cell Biology', 'Cell Biology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Academy of Periodontology', 'Periodontology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Geophysical Union', 'Geophysics');
INSERT INTO society (societyName, societyDescription) VALUES ('American Anthropological Association', 'Anthropology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Academy of Allergy, Asthma & Immunology', 'Allergy, Asthma & Immunology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society for Quality', 'Quality Management');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society for Pharmacology and Experimental Therapeutics', 'Pharmacology and Experimental Therapeutics');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society for Reproductive Medicine', 'Reproductive Medicine');
INSERT INTO society (societyName, societyDescription) VALUES ('American College of Rheumatology', 'Rheumatology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Association of Colleges of Pharmacy', 'Pharmacy Education');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society for Gastrointestinal Endoscopy', 'Gastroenterology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Academy of Forensic Sciences', 'Forensic Science');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society for Clinical Investigation', 'Clinical Investigation');
INSERT INTO society (societyName, societyDescription) VALUES ('American Academy of Child and Adolescent Psychiatry', 'Child and Adolescent Psychiatry');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society for Bioethics and Humanities', 'Bioethics and Humanities');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society for Clinical Pathology', 'Clinical Pathology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Academy of Addiction Psychiatry', 'Addiction Psychiatry');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Andrology', 'Andrology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Academy of Audiology', 'Audiology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Statistical Association', 'Statistics');
INSERT INTO society (societyName, societyDescription) VALUES ('American Association of Nurse Practitioners', 'Nurse Practitioners');
INSERT INTO society (societyName, societyDescription) VALUES ('American Academy of Cosmetic Dentistry', 'Cosmetic Dentistry');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Safety Professionals', 'Safety');
INSERT INTO society (societyName, societyDescription) VALUES ('American Academy of Physical Medicine and Rehabilitation', 'Physical Medicine and Rehabilitation');
INSERT INTO society (societyName, societyDescription) VALUES ('American Association for Cancer Research', 'Cancer Research');
INSERT INTO society (societyName, societyDescription) VALUES ('American College of Healthcare Executives', 'Healthcare Management');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Clinical Hypnosis', 'Clinical Hypnosis');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Tropical Medicine and Hygiene', 'Tropical Medicine and Hygiene');
INSERT INTO society (societyName, societyDescription) VALUES ('American Association of Pharmaceutical Scientists', 'Pharmaceutical Sciences');
INSERT INTO society (societyName, societyDescription) VALUES ('American Association of Immunologists', 'Immunology');
INSERT INTO society (societyName, societyDescription) VALUES ('American Society of Addiction Medicine', 'Addiction Medicine');
INSERT INTO society (societyName, societyDescription) VALUES ('American Association of Physicists in Medicine', 'Medical Physics');
